# Demo

In [11]:
import numpy as np

softmax_outputs = np.array([[0.7, 0.1, 0.2],
                            [0.1, 0.5, 0.4],
                            [0.02, 0.9, 0.08]])

# 0-dog | 1-cat | 2-human
# --> [dog, cat, cat]
class_targets = [0, 1, 1]

# So then we need something like the following:
# softmax_outputs[0.7, 0.1, 0.2] --------> class_targets[0] = 0 ---> 0.7
# softmax_outputs[0.1, 0.5, 0.4] --------> class_targets[1] = 1 ---> 0.5
# softmax_outputs[0.02, 0.9, 0.08] ------> class_targets[2] = 1 ---> 0.9

# -------------------------------------------
# REMINDER:

# | 0-dog (idx[0]) | 1-cat (idx[1]) | 2-human (idx[2]) |
# | -------------- | -------------- | ---------------- |
# |   0.7% (DOG)   |   0.1% (CAT)   |    0.2% (HUMAN)  |   


# softmax_outputs[0.7, 0.1, 0.2] 
# --> [index 0] 0.7% confident output = DOG
# --> [index 1] 0.1% confident output = CAT
# --> [index 2] 0.2% confident output = HUMAN

# --------> class_targets[0] = 0
# The correct output for sample 1 (class_targets[0]) was: 0 (DOG) 

# We can then look at the sample and see that the
# confidence level that the output was a DOG was 0.7
# --------------------------------------------





# -------------------
# Step 1 ------------
# -------------------

# softmax_outputs[ [0.7, 0.1, 0.2], [0.1, 0.5, 0.4],  [0.02, 0.9, 0.08] ]

# can be simplified like:
# softmax_outputs[       0        ,        1       ,           2         ]
#   ------> softmax_outputs[0,1,2]


# -------------------
# Step 2 ------------
# -------------------

# Then for the class targets, we just need the values within the array
# class_targets[0], class_targets[1], class_targets[2]

# easily turns into:
# class_targets       <-------- Remember, class_targets = [0,1,1]


# -------------------
# Step 3 ------------
# -------------------

# Finally we can simply use the following to "zip" it together
print( softmax_outputs[   [0, 1, 2],     class_targets ])

[0.7 0.5 0.9]


In [12]:
# However, we can simplify it further

# Instead of specifying the softmax_outputs "[0, 1, 2]"
# We can just check the array size by using len
print("Length:", len(softmax_outputs))



# The length is 3, so we can just the "range" feature to count from 0-3

# RECALL: ----> range(start, stop, step)
# - start (optional): where to start (DEFAULT IS 0)
# - stop (REQUIRED): where to stop (not included)
# - step (optional): increment value

# Thus, range(3) will return: 0, 1, 2


print(range( len(softmax_outputs) ))

Length: 3
range(0, 3)


In [13]:

# aka
# ----> softmax_outputs[ range(0,3), [0,1,1]
# target classes confidence
print( softmax_outputs[ range(len(softmax_outputs)), class_targets])

[0.7 0.5 0.9]


In [14]:
# Finally, to calculate the losses, just wrap what
# we wrote above, with a negative log (LOOK AT FORMULA FROM part 7)

# Output losses
print(-np.log(
    softmax_outputs[
        range(len(softmax_outputs)),
        class_targets
    ]
))

[0.35667494 0.69314718 0.10536052]


In [15]:
# Cleaned up - Calculate loss for this batch
#              as the mean of the losses

neg_log = -np.log(softmax_outputs[range(len(softmax_outputs)), class_targets])

# Then calculate our average loss
average_loss = np.mean(neg_log)
print(average_loss)

0.38506088005216804


-------------------------

Continued in `Part 8b` notebook

In [20]:
class Accuracy:
    def calculate(self, output, y_true):
        predictions = np.argmax(output, axis=1)

        if len(y_true.shape) == 2:
            y_true = np.argmax(y_true, axis=1)

        accuracy = np.mean(predictions == y_true)
        self.output = accuracy

In [21]:
softmax_outputs = np.array([[0.7, 0.2, 0.1],
                            [0.5, 0.1, 0.4],
                            [0.02, 0.9, 0.08]])

class_targets = np.array([0, 1, 1])

In [22]:
accuracy = Accuracy()
accuracy.calculate(softmax_outputs, class_targets)
print("Accuracy:", accuracy.output)

Accuracy: 0.6666666666666666
