# Loss - 0 problem

In [17]:
import numpy as np

# To consider:
# What if the confidence for the correct class is a 0?
print(-np.log(0))

inf


/tmp/ipykernel_155006/214172745.py:5: RuntimeWarning: divide by zero encountered in log
  print(-np.log(0))


In [18]:
# Modify the value at [0][0] so that it equals 0
softmax_outputs2 = np.array([[0.0, 0.1, 0.2],
                             [0.1, 0.5, 0.4],
                             [0.02, 0.9, 0.08]])

# 0-dog | 1-cat | 2-human
# --> [dog, cat, cat]
class_targets2 = [0, 1, 1]

In [19]:
# If the confidence for the correct class is 0 then the loss for the class ends up equaling INFINITY
# This is okay, as the loss value for only that output will be equal to 0
# ---------> Example output: [[  INF    0.69314718    0.10536052  ]]
neg_log2 = -np.log(softmax_outputs2[range(len(softmax_outputs2)), class_targets2])
print("Loss: ", neg_log2)
print("\n-----------------------\n")

# However, when calculating the average loss, this is where it would cause a problem
# as the average loss would equal 0 - which would be incorrect.
average_loss2 = np.mean(neg_log2)
print("Average Loss:", average_loss2)

Loss:  [       inf 0.69314718 0.10536052]

-----------------------

Average Loss: inf


/tmp/ipykernel_155006/1613827896.py:4: RuntimeWarning: divide by zero encountered in log
  neg_log2 = -np.log(softmax_outputs2[range(len(softmax_outputs2)), class_targets2])


---------------------------------------

Solution #1: Use `numpy.clip` to clip (limit) the values in an array

In [20]:
# One alternative 
import numpy as np

print("Start Range: ", -np.log(1e-7))
print("End Range: ", -np.log(1-1e-7))

Start Range:  16.11809565095832
End Range:  1.0000000494736474e-07


Note, we begin with `-np.log(1e-7)`, which is the same as $-log_{e}(1e^{-7})$

<br>

Recall **$log(x) = ln(x)$**, thus:
* $-log(1e^{-7})$
   * $-ln(1e^{-7})$
      * $-ln(10^{-7})$
         * $(-1 * -7) * ln(10)$

<br>

Given that $ln(10)$ is approximately 2.3025:
* $-ln(1e^{-7})$ 
   * ≈≈≈≈ $(7 * 2.3025)$
      *  ≈≈≈≈ **16.1180**
            * 
            

----------------------

Note, we begin with `-np.log(1-1e-7)`, which is the same as $-log_{e}(1-1e^-7)$

<br>

We will need to use Taylor Series Expansion for this.
* Recall: $-log(1-x) ≈ -x - \frac{x^{2}}{2} - \frac{x^{3}}{3} - ...$
   * For very small *x*, this simplifies to: $log(1-x) ≈ -x$
      * Thus, for $x = -1e-7$ ---------> **$-log(1 - 1e - 7) ≈ 1e - 7$**

--------------------------

In terms of `np.clip`: When *a_min* is greater than *a_max*, clip
returns an array in which all values are equal to *a_max* (see below).

```python
import numpy as np

a = np.arange(10)

# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a 

# array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])
np.clip(a, 1, 8)

# array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
np.clip(a, 8, 1)
```

In [ ]:
# Solution
y_pred_clipped = np.clip(y_pred, 0e-7, 1 - 1e-7)