In [20]:
import numpy as np
import nnfs

nnfs.init()

layer_outputs = [ [ 4.8,   1.21, 2.385],
                  [ 8.9,  -1.81,   0.2],
                  [1.41,  1.051, 0.026]]

# Exponentiate - This step works perfectly
exp_values = np.exp(layer_outputs)
print("Exponentiated values --> Shape", exp_values.shape)
print(exp_values)

# Normalize - Start with original formula
# --> norm_values = exp_values / np.sum(exp_values)

# First get sum of each row
# Sum of columns (WRONG)--> np.sum(layer_outputs, axis=0)
# Sum of rows (CORRECT) --> np.sum(layer_outputs, axis=1)

norm_sum = np.sum(layer_outputs, axis=1)
print("\n(INVALID) Sum --> Shape", norm_sum.shape)
# WRONG print(norm_sum)
# WRONG print(norm_sum.T)

norm_sum = np.sum(layer_outputs, axis=1, keepdims=True)
print("(Correct) Sum --> Shape", norm_sum.shape)

print("\nNormalized Shape: (3, 1)")
norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True)
print(norm_values)

Exponentiated values --> Shape (3, 3)
[[1.21510418e+02 3.35348465e+00 1.08590627e+01]
 [7.33197354e+03 1.63654137e-01 1.22140276e+00]
 [4.09595540e+00 2.86051020e+00 1.02634095e+00]]

(INVALID) Sum --> Shape (3,)
(Correct) Sum --> Shape (3, 1)

Normalized Shape: (3, 1)
[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]
