# Softmax Activation 

In [12]:
import numpy as np

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # We want numpy to create a weights that will be the size of
        # number of inputs times the number of neurons we want

        # The parameters of randn is the shape,
        # in this case, randn(number of columns, number of rows)
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)

        # first parameter in np.zeros is the shape
        # Remember, each neuron has a unique bias, so that is how many
        # biases we will initially generate
        self.biases = np.zeros((1, n_neurons))
        # what randn does is just a Gaussian Distribution around 0

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

In [15]:
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

# Create input/output data
X, y = spiral_data(samples=100, classes=3)

# Initialize - Layer 1:
#       2 inputs & 3 output neurons
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

# Initialize - Layer 2:
#       3 inputs & 3 output neurons
dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

# Feed inputs into Layer 1
dense1.forward(X)
activation1.forward(dense1.output)

# Feed Layer 1 outputs to Layer 2
dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])
print(activation2.output.shape)

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
(300, 3)
